### ISSUE TITLE
feat(meta): structure and content of execution-level differences

### ISSUE THREAD

**Issue by mds1** [mds1/evm-diff#4]
_This is a tracking issue, and will link out to specific issues below_

## Overview

The overall scope of the diff should be "things a smart contract developer or app developer needs to care about". For the most part, this means the diff is primarily an execution layer diff, as contract/app devs don't usually need to worry about consensus layer details. There are exceptions here, e.g. it's [easier to manipulate TWAPs](https://blog.uniswap.org/uniswap-v3-oracles) in PoS compared to PoW because an attacker knows when they'll be the block proposer for consecutive blocks. Things like this should be included.

Additionally, data should be focused on the *current* hard fork for a given chain. Including historical data when possible is great, but for now the plan it to keep it simple and focus on doing one thing—diff current EVM specs—really well.

## Data Sections

The current plan for sections is below.

In terms of implementation, always start by implementing Ethereum mainnet's spec first, and other chains' specs can import/modify that. Alternatively, another chain may import a non-mainnet chain as it's template. However, mainnet is always the chain that should be independently defined.

Adding data for any of these sections should include references. Lean towards including too many vs. too few, so things are easy to validate.

- [x] Metadata: Chain name, ID, native token name, symbol, and decimals, block explorers, etc. This is pulled from the metadata in `@wagmi/chains`.
- [x] Opcodes: This is ready to be implemented and is tracked in https://github.com/mds1/evm-diff/issues/6
- [x] Precompiles and Predeploys: This is partially implemented and needs to be finished. It's being tracked in https://github.com/mds1/evm-diff/issues/3
- [x] Transaction Types: https://github.com/mds1/evm-diff/pull/15
- [x] Account Types: https://github.com/mds1/evm-diff/issues/28
- [ ] Data structures and computation: https://github.com/mds1/evm-diff/issues/29
- [ ] Languages and Compilers: https://github.com/mds1/evm-diff/issues/30
- [ ] Gas: https://github.com/mds1/evm-diff/issues/31
- [ ] JSON-RPC: https://github.com/mds1/evm-diff/issues/32
- [x] Nodes: https://github.com/mds1/evm-diff/issues/33
- [x] Mempools: https://github.com/mds1/evm-diff/issues/34
- [ ] Block production: https://github.com/mds1/evm-diff/issues/35
- [x] Contracts: https://github.com/mds1/evm-diff/issues/36
- [ ] EIPs: https://github.com/mds1/evm-diff/issues/37
- [ ] EVM version: https://github.com/mds1/evm-diff/issues/27

## References

- https://community.optimism.io/docs/developers/bedrock/how-is-bedrock-different/
- https://developer.arbitrum.io/arbitrum-ethereum-differences
- Others linked above

**Comment by pcaversaccio** [comment]
Some further thoughts:
- I love the playground feature from https://www.evm.codes/playground: it would be a nice feature to be able to simulate the differences at opcode or Solidity level, for example.  Let me make a simple example: you have a contract compiled with solc version `0.8.20` and default EVM version `shanghai`. You copy-paste the contract into the playground, select "Optimism<>Ethereum diff" and press `run`. It will deploy on Ethereum but not on Optimism yet due to `PUSH0`. Diffs are very powerful on a documentation level, but many times you also want to understand the engineering implications. Thus, we should also think about how to integrate this best into the UI.
- Another important diff to understand is account types (e.g. EOA vs native account abstraction (such as zkSync has)).
- Also, I feel like there must be a section on the trust assumptions and differences across the different implementations. E.g. Optimism or Arbitrum are running centralised sequencers while on Ethereum anyone can participate in block producing as long as you stake 32 eth.

**Comment by protolambda** [comment]
Looking forward to evmdiff, this is a great start for some em-standardization! Even if only research, but maybe also like https://caniuse.com/ that lists all browser differences.

And +1 on showing transaction types and precompiles. It always surprises me how many extra tx types and precompiles some EVM chains, even L2s have.

And fwiw: Optimism has no custom precompiles, and only 1 extra tx type that is equivalent to EIP-1559 but without signature, for deposits from L1. And happy to answer any questions about the Optimism diff / link any useful specs.

**Comment by mds1** [comment]
Thanks @protolambda, appreciate all that! 🙌

And good call on the similarities with caniuse, haven't used it in a while so will check it out for any good ideas

**Comment by protolambda** [comment]
Some small requests:
- Separate predeploys and precompiles. The nice thing about predeploys is that external EVM tools can easily import the bytecode and support them, whereas precompiles require deeper modifications.
- Show full predeploy/precompile address on hover, or expand it on clicking, it would be handy to copy.
- compute the similarity between the two sides of text. If the text is > 80% the same, maybe highlight the differences. It's hard to find subtle changes currently.
